-- Read-only audit. Run against an isolated restoration, never publish its data.
SELECT VERSION() AS server_version, DATABASE() AS inspected_database;
SELECT TABLE_NAME, ENGINE, TABLE_COLLATION
FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() ORDER BY TABLE_NAME;
SELECT 'AUTOR_pena' AS table_name, COUNT(*) AS row_count FROM AUTOR_pena
UNION ALL SELECT 'CATEGORIA_POST_pena', COUNT(*) FROM CATEGORIA_POST_pena
UNION ALL SELECT 'CATEGORIA_pena', COUNT(*) FROM CATEGORIA_pena
UNION ALL SELECT 'CLIENTE_pena', COUNT(*) FROM CLIENTE_pena
UNION ALL SELECT 'EMAIL_pena', COUNT(*) FROM EMAIL_pena
UNION ALL SELECT 'IMAGENS_pena', COUNT(*) FROM IMAGENS_pena
UNION ALL SELECT 'LOG_pena', COUNT(*) FROM LOG_pena
UNION ALL SELECT 'PESSOA_pena', COUNT(*) FROM PESSOA_pena
UNION ALL SELECT 'POST_pena', COUNT(*) FROM POST_pena
UNION ALL SELECT 'TEMAS_pena', COUNT(*) FROM TEMAS_pena;
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'POST_pena' ORDER BY ORDINAL_POSITION;
SELECT STATUS_POST, COUNT(*) AS total FROM POST_pena GROUP BY STATUS_POST;
SELECT COUNT(*) AS total_posts,
       SUM(TRIM(LINK_POST) = '') AS empty_slugs,
       COUNT(DISTINCT LINK_POST) AS unique_slugs,
       SUM(BINARY LINK_POST NOT REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$') AS noncanonical_slugs,
       SUM(LINK_POST REGEXP '^(https?://|/)') AS absolute_or_root_links,
       MAX(CHAR_LENGTH(LINK_POST)) AS longest_slug
FROM POST_pena;
SELECT STATUS_POST, COUNT(*) AS noncanonical_slugs
FROM POST_pena WHERE BINARY LINK_POST NOT REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$' GROUP BY STATUS_POST;
SELECT CAST(ID_POST AS UNSIGNED) AS id, LINK_POST
FROM POST_pena WHERE STATUS_POST = 'PP' ORDER BY ID_POST LIMIT 5;
SELECT
  SUM(p.ID_AUTOR IS NOT NULL AND a.ID_AUTOR IS NULL) AS missing_authors,
  SUM(p.ID_PESSOA IS NOT NULL AND person.ID_PESSOA IS NULL) AS missing_people,
  SUM(p.ID_IMAGENS IS NOT NULL AND images.ID_IMAGENS IS NULL) AS missing_images,
  SUM(p.ID_CATEGORIA IS NOT NULL AND category.ID_CATEGORIA IS NULL) AS missing_categories
FROM POST_pena p
LEFT JOIN AUTOR_pena a ON a.ID_AUTOR = p.ID_AUTOR
LEFT JOIN PESSOA_pena person ON person.ID_PESSOA = p.ID_PESSOA
LEFT JOIN IMAGENS_pena images ON images.ID_IMAGENS = p.ID_IMAGENS
LEFT JOIN CATEGORIA_pena category ON category.ID_CATEGORIA = p.ID_CATEGORIA;
SELECT
  SUM(p.ID_POST IS NULL) AS missing_posts,
  SUM(c.ID_CATEGORIA IS NULL) AS missing_categories
FROM CATEGORIA_POST_pena cp
LEFT JOIN POST_pena p ON p.ID_POST = cp.ID_POST
LEFT JOIN CATEGORIA_pena c ON c.ID_CATEGORIA = cp.ID_CATEGORIA;
SELECT COUNT(*) AS existing_new_admin_or_order_tables
FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME IN ('pena_admin_users', 'pena_post_order');
SELECT 'triggers' AS object_type, COUNT(*) AS total FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA = DATABASE()
UNION ALL SELECT 'routines', COUNT(*) FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = DATABASE()
UNION ALL SELECT 'events', COUNT(*) FROM information_schema.EVENTS WHERE EVENT_SCHEMA = DATABASE();

SELECT CAST(p.ID_POST AS UNSIGNED) AS post_id, p.STATUS_POST,
       CAST(p.ID_AUTOR AS UNSIGNED) AS missing_author_id
FROM POST_pena p LEFT JOIN AUTOR_pena a ON a.ID_AUTOR = p.ID_AUTOR
WHERE p.ID_AUTOR IS NOT NULL AND a.ID_AUTOR IS NULL;
SELECT CAST(cp.ID_POST AS UNSIGNED) AS post_id, p.STATUS_POST,
       CAST(cp.ID_CATEGORIA AS UNSIGNED) AS missing_category_id
FROM CATEGORIA_POST_pena cp
LEFT JOIN CATEGORIA_pena c ON c.ID_CATEGORIA = cp.ID_CATEGORIA
LEFT JOIN POST_pena p ON p.ID_POST = cp.ID_POST
WHERE c.ID_CATEGORIA IS NULL;
SELECT STATUS_POST,
       SUM(URL_IMAGEM_POST IS NOT NULL AND TRIM(URL_IMAGEM_POST) <> '') AS direct_image_links,
       SUM(ID_IMAGENS IS NOT NULL) AS linked_media_records,
       SUM(DATA_POSTAGEM_POST IS NULL) AS missing_publication_date,
       SUM(CONTEUDO_POST IS NULL OR TRIM(CONTEUDO_POST) = '') AS empty_content
FROM POST_pena GROUP BY STATUS_POST;
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, COLUMN_COMMENT
FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE()
AND (TABLE_NAME IN ('AUTOR_pena', 'IMAGENS_pena', 'CATEGORIA_pena')
     OR (TABLE_NAME = 'POST_pena' AND COLUMN_NAME = 'STATUS_POST'))
ORDER BY TABLE_NAME, ORDINAL_POSITION;
