<!doctype html>
<html lang="pt-BR">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $post ? 'Editar artigo' : 'Novo artigo' }} | PENA</title><link rel="stylesheet" href="{{ asset('admin.css') }}"><link rel="stylesheet" href="{{ asset('admin-content.css') }}"><link rel="stylesheet" href="{{ asset('admin-posts.css') }}"><script src="{{ asset('admin-post-media.js') }}" defer></script></head>
<body>
<header class="topbar"><div class="brand">PENA <small>Veneza Piscinas</small></div><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="secondary" type="submit">Sair</button></form></header>
<main class="dashboard content-dashboard">
    <p><a href="{{ route('admin.posts.index') }}">← Voltar aos artigos</a></p>
    <h1>{{ $post ? 'Editar artigo #'.$post['row']->ID_POST : 'Criar artigo oculto' }}</h1>
    @if($post)<p>Estado atual: <strong>{{ $post['row']->STATUS_POST }}</strong>. <a href="{{ route('admin.posts.preview', $post['row']->ID_POST) }}">Ver prévia privada</a></p>@endif
    @if(session('status'))<p class="success" role="status">{{ session('status') }}</p>@endif
    @unless($canWrite)<p class="error-box" role="status">A escrita está bloqueada até a conversão/coordenação revisada do legado e a habilitação explícita no PENA.</p>@endunless
    @if($errors->any())<div class="error-box" role="alert"><p>Revise os campos indicados. Nenhuma alteração foi confirmada.</p><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @php($row = $post['row'] ?? null)
    <form method="post" action="{{ $post ? route('admin.posts.update', $row->ID_POST) : route('admin.posts.store') }}" class="form-stack content-form post-form">
        @csrf @if($post)@method('PUT')<input type="hidden" name="expected_fingerprint" value="{{ $post['fingerprint'] }}">@endif
        <label for="title">Título</label><input id="title" name="title" value="{{ old('title', $row->TITULO_POST ?? '') }}" maxlength="71" required>@error('title')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="slug">URL amigável</label><input id="slug" name="slug" value="{{ old('slug', $row->LINK_POST ?? '') }}" maxlength="200" pattern="[a-z0-9]+(-[a-z0-9]+)*" {{ $post ? 'required' : '' }}><p class="content-note">Ao criar, pode deixar vazio para gerar a partir do título. A URL de um artigo existente nunca é alterada automaticamente.</p>@error('slug')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="snippet">Resumo curto</label><textarea id="snippet" name="snippet" maxlength="156" rows="3">{{ old('snippet', $row->SNIPPET_POST ?? '') }}</textarea>@error('snippet')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="description">Descrição</label><textarea id="description" name="description" rows="3">{{ old('description', $row->DESCRICAO_POST ?? '') }}</textarea>@error('description')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="keywords">Palavras-chave</label><input id="keywords" name="keywords" value="{{ old('keywords', $row->KEYWORDS_POST ?? '') }}" maxlength="200">@error('keywords')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="html">Conteúdo HTML</label><textarea id="html" name="html" rows="18" required>{{ old('html', $row->CONTEUDO_POST ?? '') }}</textarea><p class="content-note">HTML será sanitizado no servidor. Confira a prévia depois de salvar; scripts e links inseguros são removidos.</p>@error('html')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="author_id">Autor</label><select id="author_id" name="author_id" required><option value="">Selecione um autor confirmado</option>@foreach($options['authors'] as $author)<option value="{{ $author->id }}" @selected((string) old('author_id', $post['author_id'] ?? '') === (string) $author->id)>{{ $author->signature }}</option>@endforeach</select>@error('author_id')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="main_category_id">Categoria principal</label><select id="main_category_id" name="main_category_id" required><option value="">Selecione</option>@foreach($options['categories'] as $category)<option value="{{ $category->ID_CATEGORIA }}" @selected((string) old('main_category_id', $row->ID_CATEGORIA ?? '') === (string) $category->ID_CATEGORIA)>{{ $category->NOME_CATEGORIA }}</option>@endforeach</select>@error('main_category_id')<p class="error" role="alert">{{ $message }}</p>@enderror
        <fieldset class="post-categories"><legend>Categorias vinculadas (inclua a principal)</legend>@foreach($options['categories'] as $category)<label><input type="checkbox" name="category_ids[]" value="{{ $category->ID_CATEGORIA }}" @checked(in_array((int) $category->ID_CATEGORIA, array_map('intval', old('category_ids', $post['category_ids'] ?? [])), true))> {{ $category->NOME_CATEGORIA }}</label>@endforeach</fieldset>@error('category_ids')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="media_id">Capa da biblioteca</label><select id="media_id" name="media_id"><option value="">Usar URL da capa abaixo</option>@foreach($options['media'] as $image)<option value="{{ $image->id }}" @selected(old('media_id', $post['media_id'] ?? '') === $image->id)>{{ $image->original_name }}</option>@endforeach</select><p><a href="{{ route('admin.media.index') }}" target="_blank" rel="noopener noreferrer" data-open-media-library>Abrir biblioteca para enviar ou escolher imagem (nova aba)</a></p><p class="content-note">A escolha volta a este formulário sem descartar o texto não salvo. Sem seleção automática, copie a URL na biblioteca e cole no campo abaixo.</p><p role="status" aria-live="polite" data-media-pick-status></p>@error('media_id')<p class="error" role="alert">{{ $message }}</p>@enderror
        <label for="cover_url">URL da capa existente</label><input id="cover_url" name="cover_url" value="{{ old('cover_url', $row->URL_IMAGEM_POST ?? '') }}" maxlength="200"><p class="content-note">Se uma capa da biblioteca estiver selecionada, ela terá prioridade. Nenhum arquivo antigo será apagado.</p>@error('cover_url')<p class="error" role="alert">{{ $message }}</p>@enderror
        <button type="submit" @disabled(! $canWrite || in_array($row->STATUS_POST ?? 'PO', ['PE', 'PR'], true) || (($row->STATUS_POST ?? 'PO') === 'PP' && ! auth()->user()->isAdministrator()))>Salvar artigo</button>
    </form>
    @if($post && $canWrite && !in_array($row->STATUS_POST, ['PE','PR'], true))
        <section class="panel post-actions"><h2>Estado editorial</h2><p>Publicação, ocultação e exclusão lógica são ações separadas do salvamento.</p>
            @can('publish-content')
                @if($row->STATUS_POST === 'PO')<form method="post" action="{{ route('admin.posts.publish', $row->ID_POST) }}">@csrf<input type="hidden" name="expected_fingerprint" value="{{ $post['fingerprint'] }}"><button type="submit">Publicar artigo</button></form>@endif
                @if($row->STATUS_POST === 'PP')<form method="post" action="{{ route('admin.posts.hide', $row->ID_POST) }}">@csrf<input type="hidden" name="expected_fingerprint" value="{{ $post['fingerprint'] }}"><button type="submit">Ocultar artigo</button></form>@endif
            @endcan
            @can('delete-content')<form method="post" action="{{ route('admin.posts.delete', $row->ID_POST) }}">@csrf<input type="hidden" name="expected_fingerprint" value="{{ $post['fingerprint'] }}"><label><input type="checkbox" name="confirm_delete" value="1" required> Confirmo a exclusão lógica deste artigo.</label><button class="danger-button" type="submit">Excluir logicamente</button></form>@endcan
        </section>
    @endif
</main></body></html>
